### ISSUE TITLE
0.9 release

### ISSUE THREAD

**Issue by nwolverson** [hdgarrood/purescript-ansi#3]
Would it be possible to make a release tag for the 0.9-compat changes 6077f141d7d39c6a8e5f293862a00169146be2d3 ? (That commit seems to work fine under 0.9 as far as I see)

**Comment by hdgarrood** [comment]
Certainly, when I get a moment.

**Comment by nwolverson** [comment]
Of course, it's hard to tell the difference between simply not having released yet, and what I tend to do which is to forget to (push a) tag and think it's done already.

**Comment by kritzcreek** [comment]
ping :)

**Comment by kritzcreek** [comment]
ping

**Comment by hdgarrood** [comment]
Usually I prefer to test locally before tagging, but I don't have easy access to a PC with purescript etc set up right now, so I've skipped that and I've just tagged 1.0.0. Please let me know if anything is amiss. Would one of you be able to upload it to Pursuit, please? Sorry for the delay.

**Comment by nwolverson** [comment]
Published to pursuit. Thanks!
