### ISSUE TITLE
s/Grey/Gray/g

### ISSUE THREAD

**Issue by adius** [hdgarrood/purescript-ansi#6]
1. It's of type `Color` not `Colour`
2. It's from the ANSI (**American** National Standards Institute)
3. Code is generally in American English

**Comment by adius** [comment]
I'd happily make the PR for every PureScript project if you now start to complain that it's a breaking change.

**Comment by hdgarrood** [comment]
This seems reasonable; although, an alternative might be to copy the Haskell package [`ansi-terminal`](https://hackage.haskell.org/package/ansi-terminal-0.8.0.1/docs/System-Console-ANSI-Types.html) and have a `Color` type with just 8 constructors, together with an `Intensity` type with two constructors: `Dull` and `Vivid`? That sidesteps the issue of what to call the `Gray` constructor, and is arguably a better fit for the underlying domain.

**Comment by hdgarrood** [comment]
Of course either of these will be breaking, but I don't mind releasing a breaking change when 0.12 comes out (as updating to 0.12 might well have to be a breaking change anyway).

**Comment by adius** [comment]
Yeah, that sounds even better. Good idea!
