### ISSUE TITLE
Don't print reset sequence if Array GraphicsParam is empty

### ISSUE THREAD

**Issue by adius** [hdgarrood/purescript-ansi#7]
https://github.com/hdgarrood/purescript-ansi/blob/09cef627fbdbbecc46186380da726c93b4cd6e1c/src/Ansi/Output.purs#L27

Shall I submit a PR for this?

**Comment by hdgarrood** [comment]
Seems reasonable. Do you have a specific need for this?

**Comment by adius** [comment]
=> https://en.wikipedia.org/wiki/Null_object_pattern

This means I can always call the `colorize` function and when `noColor` is set I just pass an empty array...

**Comment by adius** [comment]
Uhm ... thinking about this again, maybe it should be handled more explicitly.
Maybe it shouldn't be allow to pass a empty array at all....

**Comment by hdgarrood** [comment]
Given that the existing `withGraphics` is easy to implement using functions which are already exported from this library, I'm actually tempted to leave it as is and let users define their own variants if they have more specific needs.

**Comment by hdgarrood** [comment]
Changed my mind again. As you say, maybe it is worth changing the `EscapeCode` data type so that the `Graphics` constructor requires a non-empty array. If people are just using the helpers in `Ansi.Output` this wouldn't even necessarily be a breaking change.

**Comment by adius** [comment]
With https://pursuit.purescript.org/packages/purescript-nonempty, or how exactly do you want to do it?

**Comment by hdgarrood** [comment]
I think the `NonEmptyList` type in `lists` should be appropriate.
